### ISSUE TITLE
The given key 'Font' was not present in the dictionary.

### ISSUE THREAD

**Issue by DerpyNewb** [donkeyProgramming/TheAssetEditor#221]
StackTrace:
   at GameWorld.Core.Components.FpsComponent.Draw(GameTime gameTime) in C:\Users\ole_k\source\repos\TheAssetEditor\GameWorld\View3D\Components\FpsComponent.cs:line 38
   at GameWorld.Core.WpfWindow.WpfGame.Render(GameTime time) in C:\Users\ole_k\source\repos\TheAssetEditor\GameWorld\View3D\WpfWindow\WpfGame.cs:line 147
   
How to reproduce:
1. Closing Kitbash Viewer

**Comment by donkeyProgramming** [comment]
Can you show the copy/paste text from the error dialog? 
It does not happen locally for me so more info is needed

**Comment by donkeyProgramming** [comment]
Fixed in latest version
